### ISSUE TITLE
Poll report users count is not correct.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1008] opened 2019-05-13 09:59 UTC
Sometimes, the poll report displays the user's count incorrect:

![Screenshot from 2019-05-13 15-28-54](https://user-images.githubusercontent.com/36185596/57613165-d5da3300-7593-11e9-9b8b-4fad8829ef30.png)

**Comment by ypshukla** [comment] 2019-08-13 06:57
not fixed yet

**Comment by bogatisuman** [comment] 2019-08-20 09:20
Closed as an exact duplicate of https://github.com/congrea/virtualclass/issues/1058

**Closed by bogatisuman** 2019-08-20 09:20 UTC
Labels: Poll, Reproduced, bug

**Comment by bogatisuman** [comment] 2019-08-20 09:50
Fixed at https://github.com/bogatisuman/virtualclass/commit/94dcab7385efa2bcfe48624eaa0f9497ff9989a9
