### ISSUE TITLE
Red icon appears on the mic

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1416] opened 2020-07-24 08:24 UTC
A red icon appears on the mic when the presenter/teacher joins session with firefox browser
![mic issue](https://user-images.githubusercontent.com/38027574/88373271-30d10200-cdb5-11ea-933f-41a61ee6a3df.PNG)

**Comment by suman** [comment] 2020-09-24 08:36
Duplicate of https://github.com/congrea/virtualclass/issues/1415

**Closed by suman** 2020-09-24 08:36 UTC
Labels: Audio, bug
