### ISSUE TITLE
Private chat boxes with many users are not aligning well

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#230] opened 2016-03-22 08:50 UTC
If the number of private chats increase, the chat boxes doesn't adjust well...and overlap each other.

**Comment by meevm** [comment] 2019-06-26 06:54
The problem still exist.
![Screenshot from 2019-06-26 12-21-58](https://user-images.githubusercontent.com/12167050/60157798-37d1bd80-980d-11e9-937a-a2ad730b200a.png)

**Comment by Sudhanshu0044** [comment] 2019-08-13 10:30
Reproduced with same steps

**Comment by bogatisuman** [comment] 2019-08-31 11:14
Duplicate of https://github.com/congrea/virtualclass/issues/1098

**Closed by bogatisuman** 2019-08-31 11:14 UTC
Labels: High, Reproduced, UI, chat
