### ISSUE TITLE
After refresh hand raise gets disable on student side

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1118] opened 2019-06-25 11:08 UTC
Steps:
1. Click on hand raise on student side
2. Refresh the Congrea tab
Result: Hand raise will get hands down
![Screenshot from 2019-06-25 16-34-21](https://user-images.githubusercontent.com/38027574/60093663-a8260380-9767-11e9-851a-a09bd4f63b10.png)

**Comment by Shubhamvaishala** [comment] 2019-06-27 12:03
reproduced after refresh

**Comment by Sachi01** [comment] 2019-08-13 06:42
Reproduced

**Comment by bogatisuman** [comment] 2019-08-28 07:26
Duplicate of https://github.com/congrea/virtualclass/issues/1162

**Closed by bogatisuman** 2019-08-28 07:26 UTC
Labels: Reproduced, bug, help wanted
